dist: precise
language: python
addons:
  apt:
    packages:
    - gcc-multilib
    - lib32stdc++6
    - ash
    - bash
    - dash
    - ksh
    - mksh
    - zsh
    - pandoc
    - gdb
cache:
    - pip
    - directories:
        - usr
        - /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/
        - /home/travis/virtualenv/python2.7.13/bin/
python:
  - "3.6"
before_install:
  - echo $-
  - source travis/install.sh
  - source travis/ssh_setup.sh
  - echo $-
install:
  - pip install --upgrade pip
  - pip install --upgrade appdirs # https://github.com/ActiveState/appdirs/issues/89#issuecomment-282326570
  - pip install --upgrade --editable .
  - pip install --upgrade --requirement docs/requirements.txt
before_script:
  -echo "ok"
after_success:
  - coveralls
  - source travis/update_demo.sh
